/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux tbd-dualxeon 5.15.0-176-generic x86_64"
#define LGL_COMPILED "Sun May  3 14:48:12 CEST 2026"
#define LGL_RELEASED "Sun May  3 14:48:12 CEST 2026"
#define LGL_VERSION "1.0.0"
#define LGL_ID "d8bc21e7cd734a38355aac76fd49bf348e1b6239"
