/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux HP-12-8-2 6.8.0-57-generic x86_64"
#define LGL_COMPILED "Thu May  8 06:23:01 CEST 2025"
#define LGL_RELEASED "Thu May  8 06:23:01 CEST 2025"
#define LGL_VERSION "1.0.0"
#define LGL_ID "ce750adb0b91f80d66f9df19f70fd10178d47d85"
