/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux tbd-dualxeon 5.15.0-122-generic x86_64"
#define LGL_COMPILED "Thu Oct 24 14:59:32 CEST 2024"
#define LGL_RELEASED "Thu Oct 24 14:59:32 CEST 2024"
#define LGL_VERSION "1.0.0"
#define LGL_ID "ad6b7199556a005f4289c8e59d4b9e81c0a9e42a"
